version: '3.9'

services:
  db:
    container_name: database
    image: mysql:8.0.20
    ports:
      - '3306:3306'
    volumes:
      - bank-data:/var/lib/mysql
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: 'mysqladmin ping --silent'
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  bank-data:
